export const TOKEN_REQUESTED = 'TOKEN_REQUESTED'
export const TOKEN_REQUEST_SUCCESS = 'TOKEN_REQUEST_SUCCESS'
export const TOKEN_REQUEST_ERROR = 'TOKEN_REQUEST_ERROR'

export const LOGIN_REQUESTED = 'LOGIN_REQUESTED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILED = 'LOGOUT_FAILED'

export const USER_INFO_REQUESTED = 'USER_INFO_REQUESTED'
export const USER_INFO_REQUEST_SUCCESS = 'USER_INFO_REQUEST_SUCCESS'
export const USER_INFO_REQUEST_ERROR = 'USER_INFO_REQUEST_ERROR'

export const DISHES_REQUESTED = 'DISHES_REQUESTED'
export const DISHES_LOADED = 'DISHES_LOADED'
export const DISHES_FAILED_TO_LOAD = 'DISHES_FAILED_TO_LOAD'

export const CART_REQUESTED = 'CART_REQUESTED'
export const CART_LOADED = 'CART_LOADED'
export const CART_FAILED_TO_LOAD = 'CART_FAILED_TO_LOAD'

export const ADD_TO_CART_REQUESTED = 'ADD_TO_CART_REQUESTED'
export const ADD_TO_CART_SUCCEED = 'ADD_TO_CART_SUCCEED'
export const ADD_TO_CART_FAILED = 'ADD_TO_CART_FAILED'

export const REMOVE_FROM_CART_REQUESTED = 'REMOVE_FROM_CART_REQUESTED'
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS'
export const REMOVE_FROM_CART_FAILED = 'REMOVE_FROM_CART_FAILED'

export const CHANGE_AMOUNT_REQUESTED = 'CHANGE_AMOUNT_REQUESTED'
export const CHANGE_AMOUNT_SUCCESS = 'CHANGE_AMOUNT_SUCCESS'
export const CHANGE_AMOUNT_FAILED = 'CHANGE_AMOUNT_FAILED'

export const DISHES_IN_CART_REQUESTED = 'DISHES_IN_CART_REQUESTED'
export const DISHES_IN_CART_RECEIVED = 'DISHES_IN_CART_RECEIVED'
export const DISHES_IN_CART_FAILED_TO_RECEIVE = 'DISHES_IN_CART_FAILED_TO_RECEIVE'

export const ORDER_REQUESTED = 'ORDER_REQUESTED'
export const ORDER_REQUEST_SUCCESS = 'ORDER_REQUEST_SUCCESS'
export const ORDER_REQUEST_ERROR = 'ORDER_REQUEST_ERROR'

export const HISTORY_REQUESTED = 'HISTORY_REQUESTED'
export const HISTORY_REQUEST_SUCCESS = 'HISTORY_REQUEST_SUCCESS'
export const HISTORY_REQUEST_ERROR = 'HISTORY_REQUEST_ERROR'
